; This file stores the declarations of all event procedures

medbayAsh PROTO
jonesyJumpscare PROTO
alienHide PROTO
galleyWater PROTO
motherPanel PROTO
alienFire PROTO
nothingHappens PROTO
motherWater PROTO
podsFoundChemfuel PROTO
WCHiddenPassage PROTO
bridgeConsole PROTO
playerAttacked PROTO
thirst PROTO
strangePassage PROTO
foundItem PROTO
blankEvent PROTO
medbayGlass PROTO
start PROTO

foundWater PROTO
foundChemfuel PROTO
tooHot PROTO